[project]
name = "trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.1",
    "google-generativeai>=0.8.5",
    "pandas>=2.3.3",
    "pytest>=9.0.1",
    "python-dotenv>=1.2.1",
    "tenacity>=9.1.2",
    "trading-ig>=0.0.22",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
